### ISSUE TITLE
Release compatible version to audit4j-core 2.4.0

### ISSUE THREAD

**Issue by theborakompanioni** [audit4j/audit4j-spring#1]
When will a version compatible to audit4j-core 2.4.0 be released?

**Comment by janithb** [comment]
audit4j-spring 2.4.0 is already released and compatible with audit4j-core 2.4.0.

**Comment by theborakompanioni** [comment]
Ahh - I only looked at the tags on github.. did not search on maven central. Thanks for clarifying and the quick response.
